# Generated by Django 2.0.6 on 2019-11-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='xinxin', max_length=20)),
                ('age', models.SmallIntegerField(db_index=True)),
                ('sex', models.BooleanField(db_index=True)),
                ('salary1', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('department', models.SmallIntegerField(db_column='dept')),
                ('worktime', models.DateField(null=True, unique=True)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['age', 'name'],
            },
        ),
    ]
