# Generated by Django 2.0.6 on 2019-11-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.SmallIntegerField(db_column='dept', default=2),
        ),
    ]
