# Generated by Django 2.0.6 on 2019-11-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0008_auto_20191104_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(default=99, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='modelapp.Department'),
        ),
    ]
