# Generated by Django 2.0.6 on 2019-11-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0009_auto_20191104_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=models.SET(99), to='modelapp.Department'),
        ),
    ]
